#!/usr/bin/env python3

import os
import re

preamble = ''

if os.path.exists('makefile'):
    with open('makefile') as makefile:
        for line in makefile:
            if 'generated by makemake' in line:
                break

            preamble += line
        else:
            print('Unknown Makefile already exists')
            raise SystemExit

preamble = preamble or '''
compiler = gfortran

ifeq ($(compiler), gfortran)
  options = -std=f2003 -Wall -pedantic
endif

needless = *.mod
'''

preamble = preamble.strip()

references = {}
companions = {}
components = {}

folders = ['.']

for folder in folders:
    for file in os.listdir(folder):
        if file.startswith('.'):
            continue

        path = folder + '/' + file

        if os.path.isdir(path):
            folders.append(path)

        elif path.endswith('.f90'):
            doto = path[2:-4] + '.o'

            references[doto] = set()

            with open(path) as code:
                for line in code:
                    match = re.match(r'\s*(use|program|module)'
                        r'\s+(\w+)\s*(?:$|,)', line, re.I)

                    if match:
                        statement, name = match.groups()

                        if (statement == 'use'):
                            references[doto].add(name)

                        elif (statement == 'module'):
                            companions[name] = doto

                        elif (statement == 'program'):
                            components[name] = {doto}

for target, modules in references.items():
    references[target] = set(companions[name]
        for name in modules if name in companions)

related = set()

for doto in components.values():
    todo = list(doto)

    for target in todo:
        new = references[target] - doto

        doto |= new
        todo += new

    related |= doto

for target in references.keys():
    if target not in related:
        del references[target]

def join(these):
    return ' '.join(sorted(these))

programs = join(components)
adjuncts = join(related)

def listing(dependencies):
    return '\n'.join(target + ': ' + join(doto)
        for target, doto in sorted(dependencies.items()) if doto)

components = listing(components)
references = listing(references)

with open('makefile', 'w') as makefile:
    makefile.write('''{preamble}

# generated by makemake.py:

programs = {programs}

.PHONY: all clean cleaner

all: $(programs)

clean:
\t@rm -f $(needless) {adjuncts}

cleaner: clean
\t@rm -f $(programs)

$(programs):
\t@echo link $@
\t@$(compiler) -o $@ $^ $(external) $(external_$@)

%.o: %.f90
\t@echo compile $*
\t@$(compiler) $(options) -c $< -o $@

{components}

{references}
'''.format(**vars()))
